//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBNsite.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobsLocales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobsLocales() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QBNsite.Resources.JobsLocales", typeof(JobsLocales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2020-2022.
        /// </summary>
        public static string Caceis_Dates {
            get {
                return ResourceManager.GetString("Caceis_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trading de collatéral, traitement et suivi opérationnel des Prêts-Emprunts Titres et REPO. Réconciliation des positions avec le Back Office et avec les contreparties. Révision et amélioration des procédures de contrôles. Aide à la mise en place de la nouvelle règlementation SFTR..
        /// </summary>
        public static string Caceis_Desc {
            get {
                return ResourceManager.GetString("Caceis_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collateral trading officer.
        /// </summary>
        public static string Caceis_JobTitle {
            get {
                return ResourceManager.GetString("Caceis_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2018-2019.
        /// </summary>
        public static string Cnp_Dates {
            get {
                return ResourceManager.GetString("Cnp_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travaux de pilotage de résultats de la norme IFRS 17 avec les outils internes de CNP assurance (NEMO). Automatisation de contrôles sous SAS et VBA..
        /// </summary>
        public static string Cnp_Desc {
            get {
                return ResourceManager.GetString("Cnp_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alternant en actuariat.
        /// </summary>
        public static string Cnp_JobTitle {
            get {
                return ResourceManager.GetString("Cnp_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2022-Aujourd&apos;hui.
        /// </summary>
        public static string DriVR_Dates {
            get {
                return ResourceManager.GetString("DriVR_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Développement d&apos;une application VR de risque routier avec le moteur de jeu Unity (C#)..
        /// </summary>
        public static string DriVR_Desc {
            get {
                return ResourceManager.GetString("DriVR_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Développeur Unity VR.
        /// </summary>
        public static string DriVR_JobTitle {
            get {
                return ResourceManager.GetString("DriVR_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expériences.
        /// </summary>
        public static string Experiences {
            get {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2017.
        /// </summary>
        public static string Fractales_Dates {
            get {
                return ResourceManager.GetString("Fractales_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargé de tests de l’outil de modélisation ALM Solveo. Préparation de tests de validation de la modélisation conçue par les actuaires et implémentée dans l’outil par les développeurs JAVA..
        /// </summary>
        public static string Fractales_Desc {
            get {
                return ResourceManager.GetString("Fractales_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stagiaire en actuariat.
        /// </summary>
        public static string Fractales_JobTitle {
            get {
                return ResourceManager.GetString("Fractales_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2018.
        /// </summary>
        public static string Unicancer_Dates {
            get {
                return ResourceManager.GetString("Unicancer_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Préparation et mise en forme du rapport annuel « Bilan et perspectives »..
        /// </summary>
        public static string Unicancer_Desc {
            get {
                return ResourceManager.GetString("Unicancer_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stagiaire en data science.
        /// </summary>
        public static string Unicancer_JobTitle {
            get {
                return ResourceManager.GetString("Unicancer_JobTitle", resourceCulture);
            }
        }
    }
}
