//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBNsite.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortfolioLocales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortfolioLocales() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QBNsite.Resources.PortfolioLocales", typeof(PortfolioLocales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciel d&apos;édition de musique - En cours de dev.
        /// </summary>
        public static string BaboChill_SimpleDesc {
            get {
                return ResourceManager.GetString("BaboChill_SimpleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jeu PC FPS multijoueur en ligne qui se joue de 2 à 4 joueurs. .
        /// </summary>
        public static string ChromaClash_SimpleDesc {
            get {
                return ResourceManager.GetString("ChromaClash_SimpleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MOBA multiplateforme dans lequel deux à trois équipes équipes, composées chacune d’un joueur PC et d’un joueur mobile, s’affrontent dans une arène. .
        /// </summary>
        public static string Convergence_SimpleDesc {
            get {
                return ResourceManager.GetString("Convergence_SimpleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jeu 2D WebGL de défense de tour..
        /// </summary>
        public static string JurassicDefence_SimpleDesc {
            get {
                return ResourceManager.GetString("JurassicDefence_SimpleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adaptation numérique sous Windows Forms du jeu de société Minivilles..
        /// </summary>
        public static string Minivilles_SimpleDesc {
            get {
                return ResourceManager.GetString("Minivilles_SimpleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En savoir plus.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jeu PC de simulation d&apos;un enseignant des écoles..
        /// </summary>
        public static string SenseiSimu_SimpleDesc {
            get {
                return ResourceManager.GetString("SenseiSimu_SimpleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jeu PC de boss rush multijoueur en ligne qui se joue de 1 à 4 joueurs..
        /// </summary>
        public static string Zodiaq_SimpleDesc {
            get {
                return ResourceManager.GetString("Zodiaq_SimpleDesc", resourceCulture);
            }
        }
    }
}
