//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBNsite.Resources.League {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LeagueLocales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LeagueLocales() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QBNsite.Resources.League.LeagueLocales", typeof(LeagueLocales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It was the {0}..
        /// </summary>
        public static string GuessTheSpellAnswer {
            get {
                return ResourceManager.GetString("GuessTheSpellAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is this spell ?.
        /// </summary>
        public static string GuessTheSpellQuestion {
            get {
                return ResourceManager.GetString("GuessTheSpellQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can {0} Dash (any kind) ? .
        /// </summary>
        public static string HasDashQuestion_F {
            get {
                return ResourceManager.GetString("HasDashQuestion_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can {0} Dash (any kind) ? .
        /// </summary>
        public static string HasDashQuestion_M {
            get {
                return ResourceManager.GetString("HasDashQuestion_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does {0} have hard CC(s) in his kit ?.
        /// </summary>
        public static string HasHardCCQuestion_F {
            get {
                return ResourceManager.GetString("HasHardCCQuestion_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does {0} have hard CC(s) in his kit ?.
        /// </summary>
        public static string HasHardCCQuestion_M {
            get {
                return ResourceManager.GetString("HasHardCCQuestion_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does {0} have soft CC(s) in her kit ?.
        /// </summary>
        public static string HasSoftCCQuestion_F {
            get {
                return ResourceManager.GetString("HasSoftCCQuestion_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Does {0} have soft CC(s) in his kit ?.
        /// </summary>
        public static string HasSoftCCQuestion_M {
            get {
                return ResourceManager.GetString("HasSoftCCQuestion_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en_US.
        /// </summary>
        public static string Localisation {
            get {
                return ResourceManager.GetString("Localisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} doesn&apos;t have any {1} in her kit..
        /// </summary>
        public static string YesNoAnswerNo_F {
            get {
                return ResourceManager.GetString("YesNoAnswerNo_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} doesn&apos;t have any {1} in his kit..
        /// </summary>
        public static string YesNoAnswerNo_M {
            get {
                return ResourceManager.GetString("YesNoAnswerNo_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} can {1} with her {2}..
        /// </summary>
        public static string YesNoAnswerYes_F {
            get {
                return ResourceManager.GetString("YesNoAnswerYes_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} can {1} with his {2}..
        /// </summary>
        public static string YesNoAnswerYes_M {
            get {
                return ResourceManager.GetString("YesNoAnswerYes_M", resourceCulture);
            }
        }
    }
}
